# -*- coding: utf-8 -*-
"""Project_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mqGOH4aOsSHT9MX8Gqnq5K9T-vAES8wu
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/telecom_data.txt')
df

# How many total records are present in the file?
df['Tata Communications'].count()

# List all companies that offer 'Broadband' services.
df[df['Enterprise Solutions'] == 'Broadband']['Tata Communications']

# Count how many companies are operating in 'Delhi'.
df[df['Hyderabad']=='Kolkata']['Tata Communications'].count()

# Which companies have more than 500000 users?
df[df['465937']>500000]['Tata Communications']

# Calculate the total number of users across all records.
df['465937'].sum()

# List all unique service types present in the file.
df['Enterprise Solutions'].unique()

# Print the names of companies that have a rating of 'Excellent' and offer 'Mobile Postpaid'.
df[(df['Poor'] == 'Excellent')&(df['Enterprise Solutions'] == 'Mobile Postpaid')]['Tata Communications']

# How many companies are located in 'Mumbai' with a rating of 'Poor' or 'Below Average'?
df_mumbai = df[df['Hyderabad']=='Mumbai']
df_mumbai[(df_mumbai['Poor']=='Poor') | (df_mumbai['Poor']=='Below Average')]['Tata Communications']

# Print companies that are not offering 'Enterprise Solutions'.
df[df['Enterprise Solutions'] != 'Enterprise Solutions']['Tata Communications']

# Create a list of all companies with ratings other than 'Average'
df[df['Poor'] != 'Average']['Tata Communications']